@Weather.Api_HostAddress = http://localhost:5163/api/weather

GET {{Weather.Api_HostAddress}}/GetWeather
Accept: application/json

###
GET {{Weather.Api_HostAddress}}/forecast?city=San%20Salvador
Accept: application/json
